name: Deploy
on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy-addin:
    name: Build & Deploy AddIn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Read version from package.json
        id: read_version
        if: github.ref == 'refs/heads/main'
        uses: ActionsTools/read-json-action@main
        with:
          file_path: package.json
          prop_path: version
      - name: Set version
        id: version
        run: echo "value=${{ steps.read_version.outputs.value || 'develop' }}" >> $GITHUB_OUTPUT
      - run: npm ci
      - run: npm run build
        env:
          BASE_HREF: /addin/${{steps.version.outputs.value}}/
      - run: npm run prepare-deployment
        env:
          APP_VERSION: ${{ steps.version.outputs.value }}
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/addin/browser/
          server-dir: addin/${{steps.version.outputs.value}}/
          protocol: ftp
      - uses: actions/upload-artifact@v4
        with:
          name: manifest
          path: dist/addin/browser/manifest.xml
          if-no-files-found: error

  build-and-deploy-website:
    name: Build & Deploy Website
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm run build:website
      - run: npm run prepare-deployment
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/website/browser/
          server-dir: /
          protocol: ftp
          exclude: |
            addin/**
